name: debug secrets
on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug secrets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_URL: postgres://${{ secrets.DATABASE_USERNAME }}:${{ secrets.DATABASE_PASSWORD }}@${{ secrets.DATABASE_HOST }}:${{ secrets.DATABASE_PORT }}/postgres?schema=public
          DIRECT_URL: postgres://${{ secrets.DATABASE_USERNAME }}:${{ secrets.DATABASE_PASSWORD }}@${{ secrets.DATABASE_HOST }}:${{ secrets.DATABASE_PORT }}/postgres?schema=public
        run: echo $DATABASE_URL && echo $DIRECT_URL && echo $GH_TOKEN echo ${{ secrets.GITHUB_TOKEN }}
